baseURL: "http://haomiao2077.github.io"
languageCode: "en-us"
title: "Haomiao"
theme: "PaperMod"

minify:
  disableXML: true
  minifyOutput: true

params:
  ShowReadingTime: true
  homeInfoParams:
    Title: "Prochemga"
    Content: >
        - Welcome to Haomiao's blog. 

        - **Computer Programming**

        - **Computational Chemistry**

        - **Gaming and other things**

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]


menu:
  main:
    - name: Archive
      url: archives
      weight: 10
    - name: Search
      url: search
      weight: 20
    - name: Tags
      url: tags/
      weight: 20
    - name: Categories
      url: categories/
      weight: 20

outputs:
    home:
        - HTML
        - RSS
        - JSON
